<html>
	<head>
		<style type="text/css">
tr.d0 td {
	background-color: #CC9999; color: black;
}
tr.d1 td {
	background-color: #9999CC; color: black;
}
body {
	background-color: #3A9093;
	background-image:url('books.jpg');
	
}

h1 {
	color: blue;
	text-align: center;
}
h4{
	color:green;
}
p {
	font-family: "Times New Roman";
	font-size: 20px;
}
</style>
	</head>

	<script type="text/javascript">
	function validateForm() {
		int theory = document.forms["assignWorkForm"]["theory"].value;
		if (theory == null || theory == "") {
			alert("Please fill theory");
			return false;
		}
		int lab = document.forms["assignWorkForm"]["lab"].value;
		if (lab == null || lab == "") {
			alert("Please fill lab");
			return false;
		}
		int seminar = document.forms["assignWorkForm"]["seminar"].value;
		if (seminar == null || seminar == "") {
			alert("Please fill seminar");
			return false;
		}
		int tutorial = document.forms["assignWorkForm"]["tutorial"].value;
		if (tutorial == null || tutorial == "") {
			alert("Please fill tutorial");
			return false;
		}
		}
	}
</script>
	<body>
		<center>
			 	  <img src="logo.jpg" height="150" width="200"/>
			<h1>
				Assign Work
			</h1>
			<form name="assignWorkForm" action="./assignWork" method="post"
				onsubmit="return validateForm()">
				<table border="0" cellpadding="2" cellspacing="5">
					<tr class="d0">
						<td><h4>
							Theory Hours: // This is hardcoded
						</h4></td>
						<td>
							<select name="theory">
							<option>
								0
							</option>
							<option>
								1
							</option>
							<option>
								2
							</option>
							<option>
								3
							</option>
							<option>
								4
							</option>
							<option>
								5
							</option>
							<option>
								6
							</option>
							<option>
								7
							</option>
							<option>
								8
							</option>
							<option>
								9
							</option>
							<option>
								10
							</option>
							<option>
								11
							</option>
							<option>
								12
							</option>
							<option>
								13
							</option>
							<option>
								14
							</option>
							<option>
								15
							</option>
							<option>
								16
							</option>
							<option>
								17
							</option>
							<option>
								18
							</option>
							<option>
								19
							</option>
							<option>
								20
							</option>
							<option>
								21
							</option>
							<option>
								22
							</option>
							<option>
								23
							</option>
							<option>
								24
							</option>
							<option>
								25
							</option>
							<option>
								26
							</option>
							<option>
								27
							</option>
							<option>
								28
							</option>
							<option>
								29
							</option>
							<option>
								30
							</option>
							<option>
								31
							</option>
							<option>
								32
							</option>
							<option>
								33
							</option>
							<option>
								34
							</option>
							<option>
								35
							</option>
							<option>
								36
							</option>
							<option>
								37
							</option>
							<option>
								38
							</option>
							<option>
								39
							</option>
							<option>
								40
							</option>
							<option>
								41
							</option>
							<option>
								42
							</option>
							</select>
						</td>
					</tr>
					<tr class="d1">
						<td><h4>
							Lab Hours:
						</h4></td>
						<td>
							<select name="lab">
							<option>
								0
							</option>
							<option>
								1
							</option>
							<option>
								2
							</option>
							<option>
								3
							</option>
							<option>
								4
							</option>
							<option>
								5
							</option>
							<option>
								6
							</option>
							<option>
								7
							</option>
							<option>
								8
							</option>
							<option>
								9
							</option>
							<option>
								10
							</option>
							<option>
								11
							</option>
							<option>
								12
							</option>
							<option>
								13
							</option>
							<option>
								14
							</option>
							<option>
								15
							</option>
							<option>
								16
							</option>
							<option>
								17
							</option>
							<option>
								18
							</option>
							<option>
								19
							</option>
							<option>
								20
							</option>
							<option>
								21
							</option>
							<option>
								22
							</option>
							<option>
								23
							</option>
							<option>
								24
							</option>
							<option>
								25
							</option>
							<option>
								26
							</option>
							<option>
								27
							</option>
							<option>
								28
							</option>
							<option>
								29
							</option>
							<option>
								30
							</option>
							<option>
								31
							</option>
							<option>
								32
							</option>
							<option>
								33
							</option>
							<option>
								34
							</option>
							<option>
								35
							</option>
							<option>
								36
							</option>
							<option>
								37
							</option>
							<option>
								38
							</option>
							<option>
								39
							</option>
							<option>
								40
							</option>
							<option>
								41
							</option>
							<option>
								42
							</option>
							</select>
						</td>
					</tr>
					<tr class="d0">
						<td><h4>
							Seminar Hours:
					</h4>	</td>
						<td>
							<select name="seminar">
							<option>
								0
							</option>
							<option>
								1
							</option>
							<option>
								2
							</option>
							<option>
								3
							</option>
							<option>
								4
							</option>
							<option>
								5
							</option>
							<option>
								6
							</option>
							<option>
								7
							</option>
							<option>
								8
							</option>
							<option>
								9
							</option>
							<option>
								10
							</option>
							<option>
								11
							</option>
							<option>
								12
							</option>
							<option>
								13
							</option>
							<option>
								14
							</option>
							<option>
								15
							</option>
							<option>
								16
							</option>
							<option>
								17
							</option>
							<option>
								18
							</option>
							<option>
								19
							</option>
							<option>
								20
							</option>
							<option>
								21
							</option>
							<option>
								22
							</option>
							<option>
								23
							</option>
							<option>
								24
							</option>
							<option>
								25
							</option>
							<option>
								26
							</option>
							<option>
								27
							</option>
							<option>
								28
							</option>
							<option>
								29
							</option>
							<option>
								30
							</option>
							<option>
								31
							</option>
							<option>
								32
							</option>
							<option>
								33
							</option>
							<option>
								34
							</option>
							<option>
								35
							</option>
							<option>
								36
							</option>
							<option>
								37
							</option>
							<option>
								38
							</option>
							<option>
								39
							</option>
							<option>
								40
							</option>
							<option>
								41
							</option>
							<option>
								42
							</option>
							</select>
						</td>
					</tr>
					<tr class="d1">
						<td><h4>
							Tutorial Hours:
						</h4></td>
						<td>
								<select name="tutorial">
								<option>
									0
								</option>
								<option>
									1
								</option>
								<option>
									2
								</option>
								<option>
									3
								</option>
								<option>
									4
								</option>
								<option>
									5
								</option>
								<option>
									6
								</option>
								<option>
									7
								</option>
								<option>
									8
								</option>
								<option>
									9
								</option>
								<option>
									10
								</option>
								<option>
									11
								</option>
								<option>
									12
								</option>
								<option>
									13
								</option>
								<option>
									14
								</option>
								<option>
									15
								</option>
								<option>
									16
								</option>
								<option>
									17
								</option>
								<option>
									18
								</option>
								<option>
									19
								</option>
								<option>
									20
								</option>
								<option>
									21
								</option>
								<option>
									22
								</option>
								<option>
									23
								</option>
								<option>
									24
								</option>
								<option>
									25
								</option>
								<option>
									26
								</option>
								<option>
									27
								</option>
								<option>
									28
								</option>
								<option>
									29
								</option>
								<option>
									30
								</option>
								<option>
									31
								</option>
								<option>
									32
								</option>
								<option>
									33
								</option>
								<option>
									34
								</option>
								<option>
									35
								</option>
								<option>
									36
								</option>
								<option>
									37
								</option>
								<option>
									38
								</option>
								<option>
									39
								</option>
								<option>
									40
								</option>
								<option>
									41
								</option>
								<option>
									42
								</option>
							</select>
						</td>
						</td>
					</tr>
					<tr>
						<td>
							&nbsp;
						</td>
						<td>
							&nbsp;
						</td>
						<td>
							&nbsp;
						</td>
						<td>
							&nbsp;
						</td>
					</tr>
					<tr>
						<td>
							<input type="reset" value="Reset" />
						</td>
						<td>
							&nbsp;
						</td>
						<td>
							<input type="submit" value="Assign" />
						</td>
						<td>
							&nbsp;
						</td>
						<td>
							<td> <a href="body.jsp"><input type="button" type="button" value="Cancel" name="cancel"/></a> </td>
						</td>
						<td>
							&nbsp;
						</td>
					</tr>
				</table>
			</form>
		</center>
	</body>
</html>
